name: Publish & Notify

on:
  workflow_call:
    secrets:
      MY_GITHUB_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
    outputs:
      version:
        description: "The new package version released"
        value: ${{ jobs.publish.outputs.version }}
      releaseType:
        description: "The type of release (major, minor, patch, none)"
        value: ${{ jobs.publish.outputs.releaseType }}
      isPublished:
        description: "Whether a new release was published"
        value: ${{ jobs.publish.outputs.isPublished }}

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.new-release-version }}
      releaseType: ${{ steps.extract_release_type.outputs.release_type }}
      isPublished: ${{ steps.publish.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - name: Publish
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Extract release type
        id: extract_release_type
        run: |
          if [ -f release-info.env ]; then
            source release-info.env
            echo "release_type=${RELEASE_TYPE:-none}" >> $GITHUB_OUTPUT
          else
            echo "release_type=none" >> $GITHUB_OUTPUT
          fi

      - name: Debug Version
        run: |
          echo "version: ${{ steps.publish.outputs.new-release-version }}"
          echo "tag: ${{ steps.publish.outputs.new-release-git-tag }}"
          echo "Is Published: ${{ steps.publish.outputs.new-release-published }}"
          echo "Release Type: ${{ steps.extract_release_type.outputs.release_type }}"
          if [ -f release-info.env ]; then
            echo "Release Info Content:"
            cat release-info.env
          fi

  notify-sites:
    needs: publish
    if: needs.publish.outputs.isPublished == 'true' && needs.publish.outputs.releaseType != 'major'
    uses: psdevteamenterprise/ci-workflows/.github/workflows/update-sites-npm.yml@main
    with:
      new_version: ${{ needs.publish.outputs.version }}
    secrets:
      GH_APP_ID: ${{ secrets.APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      WIX_CLI_API_KEY: ${{ secrets.WIX_CLI_API_KEY }}
