name: Publish & Notify

on:
  workflow_call:
    inputs:
      new_version:
        description: "New version of the npm package"
        required: true
        type: string
      source_repo:
        description: "The source repository to checkout"
        required: true
        type: string
    secrets:
      MY_GITHUB_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true
      WIX_CLI_API_KEY:
        required: true
    outputs:
      version:
        description: "The new package version released"
        value: ${{ jobs.publish.outputs.version }}
      releaseType:
        description: "The type of release (major, minor, patch, none)"
        value: ${{ jobs.publish.outputs.releaseType }}
      isPublished:
        description: "Whether a new release was published"
        value: ${{ jobs.publish.outputs.isPublished }}

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.new_release_version }}
      releaseType: ${{ steps.release.outputs.release_type }}
      isPublished: ${{ steps.release.outputs.new_release_published }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} # This is the change
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_TOKEN }} # This is also needed
          
      - name: List remote tags
        run: git ls-remote --tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify-sites:
    needs: publish
    if: needs.publish.outputs.isPublished == 'true' && needs.publish.outputs.releaseType != 'major'
    uses: psdevteamenterprise/ci-workflows/.github/workflows/update-sites-npm.yml@main
    with:
      new_version: ${{ needs.publish.outputs.version }}
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      WIX_CLI_API_KEY: ${{ secrets.WIX_CLI_API_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}